name: Trigger auto deployment for src

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/src-AutoDeployTrigger-9cdbe77e-67e7-4f02-b5c7-d18ee5d58f39.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SRC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SRC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SRC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: crfaurrszfds4ek.azurecr.io
          registryUsername: ${{ secrets.SRC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SRC_REGISTRY_PASSWORD }}
          containerAppName: src
          resourceGroup: rg-naitive-agents-eus-01
          imageToBuild: crfaurrszfds4ek.azurecr.io/src:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


